### ISSUE TITLE
[enhancement] "Open With" support

### ISSUE THREAD

**Issue by SirYodaJedi** [connorh315/DATManager#2]
I noticed the application doesn't open a DAT file if you drag a DAT file onto the executable or use the file manager's "Open With" feature. This is just a simple command line argument with the path (ex: `DATManager.exe "C:\GOG Games\LEGO Star Wars - The Clone Wars\GAME1.DAT"`), so it should just be a matter of adding an argument check on launch.

silly poorly-written psuedocode to demonstrate
```py
if(exists %1):
	try:
		file.open(%1)
		app.launch()
	catch(file.ReadError):
		app.launch()
else:
	app.launch()
```

**Comment by connorh315** [comment]
Agreed, I should have had this from the beginning honestly. I'll add it ASAP, just need to fix my local repo first!

**Comment by aideniscool2** [comment]
I got the newest version and how do we use it for lego dimensions? I tired just opening with the exe but it didnt open.

**Comment by connorh315** [comment]
Version 2.3.0 now implements this, sorry Yui, I completely forgot about this.
